config/routes.rb
Rails.application.routes.draw do
  
  get 'restaurants/new'
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :restaurants
  resources :categories
  resources :dishes
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :dishes, dependent: :destroy
    belongs_to :restaurant
    validates :name, presence: true
    validates :restaurant_id, presence: true

end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :category_id, presence: true
  mount_uploader :photo, PhotoUploader

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :user
    has_many :categories, dependent: :destroy
    validates :user_id, presence:true
    validates :name, presence: true, length: { maximum: 20 }
    validates :address, presence: true, length: { maximum: 100 }
    mount_uploader :photo, PhotoUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants, dependent: :destroy
  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 返回指定字符串的哈希摘要
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # 返回一个随机令牌
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 为了持久保存会话，在数据库中记住用户
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
 
  # 如果指定的令牌和摘要匹配，返回 true
  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # 忘记用户
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  
  # def hello
  #   render html: "hello"
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        
    end
    
    def show
        @category = Category.find(params[:id])
        @dishes = @category.dishes
        @new_dish = @category.dishes.build
    end
    
    def create

        
        @restaurant = Restaurant.find(params[:restaurant_id])
        @category = @restaurant.categories.build(category_params)
        if @category.save
          redirect_to @restaurant
        else
          redirect_to @restaurant
        end
    end
  
    private

    def category_params
      params.require(:category).permit(:name, :restaurant_id)
    end
    
    
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
    def new
        
    end
    
    def show
        @dish = Dish.find(params[:id])
    end
    
    def create
        @category = Category.find(params[:category_id])
        @dish = @category.dishes.build(dish_params)
        if @dish.save
          redirect_to @category
        else
          redirect_to @category
        end
    end
    
    def update
      @dish = Dish.find(params[:id])
      if @dish.update_attributes(dish_params)
        flash[:success]= "Updated"
        redirect_to @dish
      else
        redirect_to @dish
      end
    end
    private
    
    def dish_params
      params.require(:dish).permit(:name, :category_id, :price)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def new
        @restaurant = current_user.restaurants.build
    end
    
    def index
        @restaurants = Restaurant.all
    end
    
    def show
        @restaurant = Restaurant.find(params[:id])
        @categories = @restaurant.categories
        @new_category = @restaurant.categories.build

    end
    
    def create
        @user = current_user
        @restaurant = @user.restaurants.build(restaurant_params)
        if @restaurant.save
          redirect_to restaurants_path
        else
          render 'new'
        end
    end
  
    private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :photo, :users)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # 登入用户，然后重定向到用户的资料页面
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_url
    else
      # 创建一个错误消息
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @restaurants = Restaurant.all
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show 
    @user = User.find(params[:id])
    
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user #login after signup
      # 处理注册成功的情况
      flash[:success] = "Welcome to the Online Order System!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 返回当前登录的用户（如果有的话）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # 如果用户已登录，返回 true，否则返回 false
  def logged_in?
    !current_user.nil?
  end  
  
  # 在持久会话中记住用户
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # # 返回 cookie 中记忆令牌对应的用户
  # def current_user
  #   if (user_id = session[:user_id]) #如果会话中有用户的 ID，把会话中的 ID 赋值给 user_id
  #     @current_user ||= User.find_by(id: user_id)
  #   elsif (user_id = cookies.signed[:user_id])
  #     raise       # 测试仍能通过，所以没有覆盖这个分支
  #     user = User.find_by(id: user_id)
  #     if user && user.authenticated?(cookies[:remember_token])
  #       log_in user
  #       @current_user = user
  #     end
  #   end
  # end

  # 忘记持久会话
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  

  # 退出当前用户
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 返回指定用户的 Gravatar
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/categories/_dish_form.html.erb
<%= form_for(@new_dish) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :price %>
    <%= f.text_field :price, class:'form-control' %>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
    <%= hidden_field_tag :category_id, @category.id %>
    <%= f.submit "add", class: "btn btn-primary" %>
<% end %>

app/views/categories/index.html.erb
<% @categories.each do |rest| %>
    <%= link_to rest.name, rest %>
    <br>
<% end %>

<%= link_to "New Category", categories_new_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= @category.name %>
<br>
<% @category.dishes.each do |dish| %>
    <%= link_to dish.name , dish %> 
    <%= dish.price %>
    <br>
<% end %>
<% if current_user.id == @category.restaurant.user_id %>
New Dish
<%= render partial: 'categories/dish_form'%>
<% end %>

app/views/dishes/edit.html.erb
<% provide(:title, "Edit dish") %>
<h1>Update your dish</h1>
<%= form_for(@dish) do |d| %> 
    <%= d.label :name %>
    <%= d.text_field :name, class:'form_control' %>
    <%= d.label :price %>
    <%= d.text_field :price, class:'form_control' %>
<% end %>

app/views/dishes/show.html.erb
<%= @dish.name %>
<%= @dish.price %>
<%= image_tag(@dish.photo_url) %>
<br>
<% provide(:title, "Edit dish") %>
<h1>Update your dish</h1>
<% if current_user.id == @dish.category.restaurant.user_id %>
    <%= form_for(@dish) do |d| %> 
        <%= d.label :name %>
        <%= d.text_field :name, class:'form_control' %>
        <%= d.label :price %>
        <%= d.text_field :price, class:'form_control' %>
        <%= d.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Online Order System", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>

app/views/restaurants/_category_form.html.erb
<%= form_for(@new_category) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= hidden_field_tag :restaurant_id, @restaurant.id %>
    <%= f.submit "add", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/_dish_form.html.erb
<%= form_for @new_dish do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :price %>
    <%= f.number_field :price, :step => "0.01", class: 'form-control' %>
    

   
    <%= f.label @category.id %>
    <%= hidden_field_tag :category_id, @category.id %>
    
    <%= f.submit "add dish", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
    
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
    
    <%= f.submit "Create Restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<% if logged_in? %>
    <% @restaurants.each do |rest| %>
        <% if current_user.id == rest.user_id %>
            <%= link_to rest.name, rest %>
            <%= rest.address %>
            <%= image_tag(rest.photo_url) %>
            <br>
        <% end %>
    <% end %>
    <%= link_to "New Restaurant", restaurants_new_path %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<%= @restaurant.name %>
<%= @restaurant.address %>
<%= image_tag(@restaurant.photo_url) %>
<br>
<% @restaurant.categories.each do |cat| %>
    <%= link_to cat.name, cat %>
    <br>
<% end %>
<% if current_user.id == @restaurant.user_id %>
    New Category
    <%= render partial: 'restaurants/category_form'%>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Help Content.
</p>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Online Order System</h1>

  <h2>
    This is the home page for the Online Ordering System
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% @restaurants.each do |rest| %>
  <%= link_to rest.name, rest %>
  <%= rest.address %>
  <%= image_tag(rest.photo_url) %>
  <br>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>


      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>